version: '3.7'

services:
  db:
    image: registry.tochka-tech.com/proxy_docker-io/library/postgres:11.5-alpine
    environment:
      POSTGRES_DB: "eventtracker"
      POSTGRES_USER: "eventtracker"
      POSTGRES_PASSWORD: "eventtracker_passwd"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
